Move over config and instructions from NTAP/isb-ietf-config.
ietf/terminology pull request #18
Opened 2021-11-02 12:15 UTC by larseggert

Fixes #14.

2021-11-02 16:57 UTC, jimfenton requested changes
If IETF is adopting the [NIST guidance on using inclusive language](https://nvlpubs.nist.gov/nistpubs/ir/2021/NIST.IR.8366.pdf), these warnings should be consistant with that guidance. I have pointed out a couple of places where these warnings go beyond the NIST guidance; there may be others as well (I didn't exhaustively check).

2021-11-02 16:57 UTC, jimfenton commented on .github/in-solidarity.yml
> +      - /\btradition\w*\b/gi
This is not in the NIST guidance.

2021-11-02 16:57 UTC, jimfenton commented on .github/in-solidarity.yml
> +      - /\belder\w*\b/gi
While the NIST guidance does suggest caution on the use of "elderly", it does not suggest that alternate words be used. Some people would consider "old" to be more pejorative as an elder often conveys a sense of wisdom.

2021-11-03 11:45 UTC, larseggert commented on .github/in-solidarity.yml
> +      - /\btradition\w*\b/gi
The RFC Editor is also using "Table 1" at https://www.nist.gov/nist-research-library/nist-technical-series-publications-author-instructions#inclusive, which includes that term.

2021-11-03 11:46 UTC, larseggert commented on .github/in-solidarity.yml
> +      - /\belder\w*\b/gi
Should we than rather remove "old" from the suggestions?

2021-11-03 12:55 UTC, ekr commented on .github/in-solidarity.yml
> +      - /\b(he|him|his|she|her|hers)\b/gi
This is going to cause a lot of false positives because many of our examples in documents use "Alice", "Bob", etc, combined with gendered pronouns to refer to their actions.

2021-11-03 12:55 UTC, ekr commented on .github/in-solidarity.yml
> +      - /\belder\w*\b/gi
Well, do we intend to stop giving the RFC Editor changes in the form of "OLD/NEW"?

2021-11-03 17:56 UTC, larseggert commented on .github/in-solidarity.yml
> +      - /\belder\w*\b/gi
Why would those be hit by the regex?

2021-11-03 17:57 UTC, larseggert commented on .github/in-solidarity.yml
> +      - /\b(he|him|his|she|her|hers)\b/gi
Yeah, it also often hits on acronym text. (I use this regex list as part of https://github.com/larseggert/ietf-reviewtool)

2021-11-03 18:00 UTC, ekr commented on .github/in-solidarity.yml
> +      - /\belder\w*\b/gi
They wouldn't with this regex, but if we think "old" is to be avoided, then what does that imply for that usage?

2021-11-03 19:56 UTC, jimfenton commented on .github/in-solidarity.yml
> +      - /\btradition\w*\b/gi
When IETF decided to use the 'NIST Guidance', I assumed that meant NISTIR 8366 although I don't remember the exact sequence of events (perhaps this was done before 8366 came out; I don't remember). And I'm rather surprised that there are significant differences between the two NIST documents. Should I point out the inconsistency to NIST and ask them which set of guidelines is authoritative?

2021-11-03 19:59 UTC, jimfenton commented on .github/in-solidarity.yml
> +      - /\belder\w*\b/gi
I'm definitely not the one to decide whether 'old' is to be avoided, even if it is used in the context of referring to persons of a certain age. But I am curious where the avoidance of 'elder', and its suggested replacements, came from.

2021-11-03 20:20 UTC, larseggert commented on .github/in-solidarity.yml
> +      - /\belder\w*\b/gi
It's in the same table from NIST that has "traditional".

2021-11-04 07:52 UTC, larseggert commented on .github/in-solidarity.yml
> +      - /\btradition\w*\b/gi
The IETF did decide to use NISTIR 8366. The RFC Editor decided (I guess) that the web link with "Table 1" provided them good practical information, and so they started referring to it.

2021-11-09 14:29 UTC, sginoza commented on .github/in-solidarity.yml
> +      - /\btradition\w*\b/gi
NISTR 8366 includes the following: 

  Table 1 was extracted in part to show examples of sentences with potentially biased language 
  along with suggestions for unbiased alternatives. The full table can be found on the NIST website.

where "NIST website" links to <https://www.nist.gov/nist-research-library/nist-technical-series-publications-author-instructions#table1>.  We interpreted the adoption of NISTR 8366 to include the full table since that is what the document points to, and we discussed our intent at a meeting with the stream managers.  If we should be limiting our checks to the words listed in table 1 of NISTR 8366 (i.e., not the full table), we are happy to adjust.

2021-11-09 22:48 UTC, jimfenton commented on .github/in-solidarity.yml
> +      - /\btradition\w*\b/gi
My concern with both Table 1 in NISTIR 8366 and in nist-technical-series-publications-author-instructions is that they are captioned, "Examples of *potentially* biased language..." (emphasis added). The real guidance is in the principles in the bullet points that precede the table. I'm concerned that using the entries from the table to drive a regex is that the table will be taken literally, without regard for context. But I really don't know how this collection of regexes is going to be used, so perhaps I'm overreacting.

2021-11-11 07:54 UTC, larseggert commented on .github/in-solidarity.yml
> +      - /\btradition\w*\b/gi
@jimfenton please see the change to the notification message I just pushed, which I hope will make it clear(er) that pattern-matching is used and false positives should be expected.

2021-11-11 09:13 UTC, jimfenton approved these changes
Much better; thanks for the updated wording.

A nit: *pattern matching* and *pull request* are not commonly hyphenated.

2021-11-11 10:30 UTC, merged